# Render Blueprint for Backend API Service
services:
  - type: web
    name: builder-backend
    env: node
    # Point to the root directory where package.json is located
    root: ..
    # Build command (runs from the root directory)
    buildCommand: npm install
    # Start command (runs from the root directory)
    startCommand: node backend/start-server.js
    # Health check path (make sure this endpoint exists in your backend)
    healthCheckPath: /api/health
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        required: true
      - key: JWT_SECRET
        required: true
        generateValue: true
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Render automatically assigns a port, but we can specify a default
      - key: MONGODB_URI
        required: true
        # This should be set in your Render dashboard
        generateValue: true
      - key: JWT_SECRET
        required: true
        generateValue: true
    # Health check path
    healthCheckPath: /api/health
    # Auto-deploy from Git
    autoDeploy: true
    # Region (choose one closest to your users)
    region: oregon  # Options: oregon, ohio, frankfurt, singapore, sydney
    # Plan type
    plan: free  # Options: free, starter, standard, plus, pro, pro_plus, pro_max
    # Instance type (for paid plans)
    # instanceType: free  # For free plan
    # instanceType: starter  # For starter plan and above
    # Scaling
    numInstances: 1
    # Build environment
    build:
      nodeVersion: 18.x  # Match your local Node.js version
